apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-onboarding-demo
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sprakriy/ArgoCD-multi-repo-pipeline.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: 'app-{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sprakriy/ArgoCD-multi-repo-pipeline.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
